[2022-12-29T21:02:46.483+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: a_initial_load.create_database scheduled__2022-12-28T00:00:00+00:00 [queued]>
[2022-12-29T21:02:46.489+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: a_initial_load.create_database scheduled__2022-12-28T00:00:00+00:00 [queued]>
[2022-12-29T21:02:46.489+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-29T21:02:46.489+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-29T21:02:46.489+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-29T21:02:46.499+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): create_database> on 2022-12-28 00:00:00+00:00
[2022-12-29T21:02:46.505+0000] {standard_task_runner.py:55} INFO - Started process 1241 to run task
[2022-12-29T21:02:46.508+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'a_initial_load', 'create_database', 'scheduled__2022-12-28T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/initial_load.py', '--cfg-path', '/tmp/tmpbpbd1q1b']
[2022-12-29T21:02:46.510+0000] {standard_task_runner.py:83} INFO - Job 23: Subtask create_database
[2022-12-29T21:02:46.557+0000] {task_command.py:389} INFO - Running <TaskInstance: a_initial_load.create_database scheduled__2022-12-28T00:00:00+00:00 [running]> on host 617cc505ea19
[2022-12-29T21:02:46.615+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=a_initial_load
AIRFLOW_CTX_TASK_ID=create_database
AIRFLOW_CTX_EXECUTION_DATE=2022-12-28T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-28T00:00:00+00:00
[2022-12-29T21:02:46.622+0000] {logging_mixin.py:137} INFO - CREATE DATABASE stocks
[2022-12-29T21:02:46.656+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-12-29T21:02:46.788+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=a_initial_load, task_id=create_database, execution_date=20221228T000000, start_date=20221229T210246, end_date=20221229T210246
[2022-12-29T21:02:46.838+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-12-29T21:02:46.865+0000] {taskinstance.py:2582} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-12-29T21:11:12.698+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: a_initial_load.create_database scheduled__2022-12-28T00:00:00+00:00 [queued]>
[2022-12-29T21:11:12.704+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: a_initial_load.create_database scheduled__2022-12-28T00:00:00+00:00 [queued]>
[2022-12-29T21:11:12.704+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-29T21:11:12.704+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-29T21:11:12.704+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-29T21:11:12.716+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): create_database> on 2022-12-28 00:00:00+00:00
[2022-12-29T21:11:12.724+0000] {standard_task_runner.py:55} INFO - Started process 2133 to run task
[2022-12-29T21:11:12.727+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'a_initial_load', 'create_database', 'scheduled__2022-12-28T00:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/initial_load.py', '--cfg-path', '/tmp/tmp982l2d5g']
[2022-12-29T21:11:12.729+0000] {standard_task_runner.py:83} INFO - Job 26: Subtask create_database
[2022-12-29T21:11:12.772+0000] {task_command.py:389} INFO - Running <TaskInstance: a_initial_load.create_database scheduled__2022-12-28T00:00:00+00:00 [running]> on host 617cc505ea19
[2022-12-29T21:11:12.836+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=a_initial_load
AIRFLOW_CTX_TASK_ID=create_database
AIRFLOW_CTX_EXECUTION_DATE=2022-12-28T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-28T00:00:00+00:00
[2022-12-29T21:11:12.843+0000] {logging_mixin.py:137} INFO - CREATE DATABASE stocks
[2022-12-29T21:11:12.844+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/initial_load.py", line 199, in create_database
    cursor.execute(sql)
psycopg2.errors.DuplicateDatabase: database "stocks" already exists

[2022-12-29T21:11:12.852+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=a_initial_load, task_id=create_database, execution_date=20221228T000000, start_date=20221229T211112, end_date=20221229T211112
[2022-12-29T21:11:12.863+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 26 for task create_database (database "stocks" already exists
; 2133)
[2022-12-29T21:11:12.897+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-29T21:11:12.922+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-12-29T21:12:13.416+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: a_initial_load.create_database scheduled__2022-12-28T00:00:00+00:00 [queued]>
[2022-12-29T21:12:13.423+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: a_initial_load.create_database scheduled__2022-12-28T00:00:00+00:00 [queued]>
[2022-12-29T21:12:13.423+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-29T21:12:13.423+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-29T21:12:13.423+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-29T21:12:13.434+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): create_database> on 2022-12-28 00:00:00+00:00
[2022-12-29T21:12:13.441+0000] {standard_task_runner.py:55} INFO - Started process 2236 to run task
[2022-12-29T21:12:13.444+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'a_initial_load', 'create_database', 'scheduled__2022-12-28T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/initial_load.py', '--cfg-path', '/tmp/tmptzxksbh2']
[2022-12-29T21:12:13.445+0000] {standard_task_runner.py:83} INFO - Job 27: Subtask create_database
[2022-12-29T21:12:13.495+0000] {task_command.py:389} INFO - Running <TaskInstance: a_initial_load.create_database scheduled__2022-12-28T00:00:00+00:00 [running]> on host 617cc505ea19
[2022-12-29T21:12:13.560+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=a_initial_load
AIRFLOW_CTX_TASK_ID=create_database
AIRFLOW_CTX_EXECUTION_DATE=2022-12-28T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-28T00:00:00+00:00
[2022-12-29T21:12:13.567+0000] {logging_mixin.py:137} INFO - CREATE DATABASE stocks
[2022-12-29T21:12:13.598+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-12-29T21:12:13.610+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=a_initial_load, task_id=create_database, execution_date=20221228T000000, start_date=20221229T211213, end_date=20221229T211213
[2022-12-29T21:12:13.655+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-12-29T21:12:13.679+0000] {taskinstance.py:2582} INFO - 1 downstream tasks scheduled from follow-on schedule check
