[2022-12-29T22:43:35.039+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: a_initial_load.create_views scheduled__2022-12-28T00:00:00+00:00 [queued]>
[2022-12-29T22:43:35.045+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: a_initial_load.create_views scheduled__2022-12-28T00:00:00+00:00 [queued]>
[2022-12-29T22:43:35.045+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-29T22:43:35.045+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-29T22:43:35.045+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-29T22:43:35.057+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): create_views> on 2022-12-28 00:00:00+00:00
[2022-12-29T22:43:35.066+0000] {standard_task_runner.py:55} INFO - Started process 11770 to run task
[2022-12-29T22:43:35.070+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'a_initial_load', 'create_views', 'scheduled__2022-12-28T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/initial_load.py', '--cfg-path', '/tmp/tmppti1yrru']
[2022-12-29T22:43:35.072+0000] {standard_task_runner.py:83} INFO - Job 29: Subtask create_views
[2022-12-29T22:43:35.181+0000] {task_command.py:389} INFO - Running <TaskInstance: a_initial_load.create_views scheduled__2022-12-28T00:00:00+00:00 [running]> on host 617cc505ea19
[2022-12-29T22:43:35.250+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=a_initial_load
AIRFLOW_CTX_TASK_ID=create_views
AIRFLOW_CTX_EXECUTION_DATE=2022-12-28T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-28T00:00:00+00:00
[2022-12-29T22:43:35.251+0000] {logging_mixin.py:137} INFO - AAPL
[2022-12-29T22:43:35.985+0000] {logging_mixin.py:137} INFO - GOOGL
[2022-12-29T22:43:36.423+0000] {logging_mixin.py:137} INFO - MSFT
[2022-12-29T22:43:37.016+0000] {logging_mixin.py:137} INFO - IBM
[2022-12-29T22:43:37.427+0000] {logging_mixin.py:137} INFO - NVDA
[2022-12-29T22:43:38.074+0000] {logging_mixin.py:137} INFO - ORCL
[2022-12-29T22:43:38.476+0000] {logging_mixin.py:137} INFO - INTC
[2022-12-29T22:43:39.066+0000] {logging_mixin.py:137} INFO - QCOM
[2022-12-29T22:43:39.505+0000] {logging_mixin.py:137} INFO - AMD
[2022-12-29T22:43:39.791+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/initial_load.py", line 114, in create_views
    create_view(stock_id)
  File "/opt/airflow/dags/initial_load.py", line 107, in create_view
    temp_table_wtime=psycopg2.sql.Identifier(temp_table_wtime)))
psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

[2022-12-29T22:43:39.800+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=a_initial_load, task_id=create_views, execution_date=20221228T000000, start_date=20221229T224335, end_date=20221229T224339
[2022-12-29T22:43:39.809+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 29 for task create_views (server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
; 11770)
[2022-12-29T22:43:39.850+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-29T22:43:39.874+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
